version: '3.7'

services:
  app:
    build: .
    image: trading-ace
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - trading-ace-network
  
  postgres:
    image: postgres:14.15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: trading-ace
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - trading-ace-network

  redis:
    image: redis:7.4.1-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes: 
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - trading-ace-network

networks:
  trading-ace-network:
    driver: bridge

volumes:
  pg-data:
  redis-data: